### ISSUE TITLE
Render images as png instead of jpeg?

### ISSUE THREAD

**Issue by hubdotcom** [CharlieHess/slack-poker-bot#44]
Improve quality and lower file size

**Comment by stephenyeargin** [comment]
Source files are in [here](https://github.com/CharlieHess/slack-poker-bot/tree/master/resources) if anyone gives this a spin. Not sure what the license is on the card images.

[Imgur](https://www.npmjs.com/package/imgur), the current rendering library, [seems to prefer JPG](https://imgur.userecho.com/topic/93338-png-file-changes-to-jpg-when-uploaded/) because it renders at a lower file size? So the source files may be PNG, but it may still spit back a JPG.

**Comment by hubdotcom** [comment]
Most likely since the input are JPG's - converting a PNG will retain the artefacts introduced by the JPG and output a high file size - but combining graphical PNG's retains the low file size. I've tested with PNG's on the output and seems to work good. 

Did you manually rename all those jpeg cards?

**Comment by CharlieHess** [comment]
I'd take a PR for this, so long as it passes tests.

**Comment by hubdotcom** [comment]
See https://github.com/CharlieHess/slack-poker-bot/pull/46

Resources still need generating in a png format for maximum efficiency

**Comment by hubdotcom** [comment]
It doesn't appear the function toBuffer is used in the app?
https://github.com/CharlieHess/slack-poker-bot/search?utf8=%E2%9C%93&q=toBuffer

**Comment by CharlieHess** [comment]
Fixed in #48.
